spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:./target/classes/data/avaliacao;AUTO_SERVER=true
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  flyway:
    user: sa
    password: sa
    url: jdbc:h2:file:./target/classes/data/avaliacao;AUTO_SERVER=true
    locations: filesystem:src/main/resources/db/migration
    baseline-on-migrate: true
    clean-on-validation-error: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      type:
        deor:
          sql:
            BasicBinder: TRACE

cliente:
  message001: Nao existe cliente com este id
  message002: Um novo cliente nao pode ter um id

jwt:
  secret: 562455166
  expiration: 86400000