spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:avaliacao
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  flyway:
    user: sa
    password: sa
    schemas: avaliacao
    clean-on-validation-error: true

jwt:
  secret: 562455166
  expiration: 86400000
