CREATE TABLE TELEFONE
(
    ID         NUMBER(11) AUTO_INCREMENT,
    NUMERO     VARCHAR(15),
    TIPO       VARCHAR(15),
    CLIENTE_ID NUMBER(11),
    CONSTRAINT TELEFONE_PK PRIMARY KEY (ID),
    CONSTRAINT TELEFONE_CLIENTE_FK FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (ID)
);
