CREATE TABLE CLIENTE
(
    ID          NUMBER(11) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NOME        VARCHAR(100),
    CPF         VARCHAR(11),
    CEP         VARCHAR(100),
    LOGRADOURO  VARCHAR(100),
    BAIRRO      VARCHAR(100),
    LOCALIDADE  VARCHAR(100),
    UF          VARCHAR(100),
    UNIDADE     VARCHAR(100),
    IBGE        VARCHAR(100),
    COMPLEMENTO VARCHAR(100),
    CONSTRAINT CLIENTE_PK PRIMARY KEY (ID)
);
