CREATE TABLE TELEFONE
(
    ID         NUMBER(11) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NUMERO     VARCHAR(15),
    TIPO       VARCHAR(15),
    CLIENTE_ID NUMBER(11),
    CONSTRAINT TELEFONE_PK PRIMARY KEY (ID),
    CONSTRAINT TELEFONE_CLIENTE_FK FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (ID)
);
