CREATE TABLE USERS
(
    ID       NUMBER(11) AUTO_INCREMENT,
    LOGIN    VARCHAR(100),
    PASSWORD VARCHAR(100),
    ROLE     VARCHAR(100),
    CONSTRAINT USERS_PK PRIMARY KEY (ID),
    CONSTRAINT CHECK_ROLES CHECK (ROLE = 'ADMIN' OR ROLE = 'COMUM')
);
