INSERT INTO USERS (LOGIN, PASSWORD, ROLE)
VALUES ('admin', '$2y$12$Je6OWTg0hh.Ie/kISwxJo.ehWUNuXti6yk4f74BG7oA45NkDIvvuS', 'ADMIN');

INSERT INTO USERS (LOGIN, PASSWORD, ROLE)
VALUES ('comum', '$2y$12$Je6OWTg0hh.Ie/kISwxJo.ehWUNuXti6yk4f74BG7oA45NkDIvvuS', 'COMUM');