-- Usuario
INSERT INTO USERS (LOGIN, PASSWORD, ROLE)
VALUES ('admin', '$2y$12$Je6OWTg0hh.Ie/kISwxJo.ehWUNuXti6yk4f74BG7oA45NkDIvvuS', 'ADMIN');

INSERT INTO USERS (LOGIN, PASSWORD, ROLE)
VALUES ('comum', '$2y$12$Je6OWTg0hh.Ie/kISwxJo.ehWUNuXti6yk4f74BG7oA45NkDIvvuS', 'COMUM');

-- Cliente
INSERT INTO CLIENTE (NOME, CPF, CEP, LOGRADOURO, BAIRRO, LOCALIDADE, UF, UNIDADE, IBGE, COMPLEMENTO)
VALUES ('Brad Gibson', '58454286020', '69425-970', 'Rua Getúlio Vargas', 'Centro', 'Caapiranga', 'AM', null, null,
        'Casa');
INSERT INTO EMAIL (EMAIL, CLIENTE_ID)
VALUES ('brad.gibson@gmail.com', 1);
INSERT INTO TELEFONE (NUMERO, TIPO, CLIENTE_ID)
VALUES ('619847365', 'CELULAR', 1)